### ISSUE TITLE
Resizing the cropper window

### ISSUE THREAD

**Issue by Yashar78** [erjieyong/streamlit-cropperjs#1]
I really like the component :) . I am dealing with large images ( 2500x3500) and when I open it I have to scroll down to make a cropping.
Is there a way to fit it in the screen without loosing the original resolution of the crops ?

**Comment by erjieyong** [comment]
Hi @Yashar78 , I've added size option, you can tweak the size value now to increase or decrease the crop window as necessary.

```
cropped_pic = st_cropperjs(pic=pic, btn_text="Detect!", size=0.5, key="foo")
```
